package com.example.util

enum class AppLanguage(val code: String, val displayName: String) {
    ENGLISH("en", "English"),
    HINDI("hi", "हिन्दी"),
    MARATHI("mr", "मराठी")
}

object AppStrings {
    fun get(key: String, lang: String): String {
        val strings = when (lang) {
            "hi" -> hindiStrings
            "mr" -> marathiStrings
            else -> englishStrings
        }
        return strings[key] ?: englishStrings[key] ?: key
    }

    private val englishStrings = mapOf(
        "app_title" to "HisabPro",
        "home" to "Home",
        "sales" to "Sales",
        "parties" to "Parties",
        "reports" to "Reports",
        "more" to "More",
        "business_setup" to "Business Setup",
        "business_name" to "Business / Shop Name",
        "phone_number" to "Phone Number",
        "address" to "Address",
        "state" to "State",
        "gst_registered_q" to "GST Registered Business?",
        "gstin" to "GSTIN (15 Digits)",
        "pan" to "PAN Number",
        "composition_scheme" to "Composition Scheme (1% or 6%)",
        "save_details" to "Save Details",
        "todays_sales" to "Today's Sales",
        "total_receivables" to "Total Receivables",
        "you_will_get" to "You Will Get (Dr)",
        "total_payables" to "Total Payables",
        "you_will_give" to "You Will Give (Cr)",
        "cash_bank_balance" to "Cash & Bank Balance",
        "quick_actions" to "Quick Actions",
        "add_sale" to "+ Sale Bill",
        "receive_payment" to "+ Receive Money",
        "add_party" to "+ Add Party",
        "add_expense" to "+ Add Expense",
        "recent_invoices" to "Recent Invoices",
        "no_invoices" to "No invoices created yet",
        "customers" to "Customers",
        "suppliers" to "Suppliers",
        "opening_balance" to "Opening Balance",
        "current_balance" to "Current Balance",
        "add_new_party" to "Add New Party",
        "customer" to "Customer",
        "supplier" to "Supplier",
        "both" to "Both",
        "receivable_dr" to "Receivable (Dr)",
        "payable_cr" to "Payable (Cr)",
        "create_invoice" to "Create Sale Bill",
        "invoice_no" to "Invoice No",
        "date" to "Date",
        "select_party" to "Select Customer",
        "non_gst_bill" to "Non-GST Bill (Simple)",
        "gst_tax_invoice" to "GST Tax Invoice",
        "item_name" to "Item Description",
        "qty" to "Qty",
        "unit" to "Unit",
        "rate" to "Rate (₹)",
        "amount" to "Amount",
        "add_item" to "+ Add Item",
        "subtotal" to "Subtotal",
        "cgst" to "CGST",
        "sgst" to "SGST",
        "igst" to "IGST",
        "total_amount" to "Total Amount",
        "paid_amount" to "Paid Amount",
        "balance_due" to "Balance Due",
        "payment_mode" to "Payment Mode",
        "save_invoice" to "Save & Preview Invoice",
        "payment_received" to "Payment Received",
        "received_from" to "Received From",
        "reference_no" to "Reference / UPI / Cheque No",
        "notes" to "Notes / Narration",
        "save_payment" to "Record Payment",
        "daily_sales" to "Daily Sales",
        "outstanding_report" to "Outstanding Ledger",
        "day_book" to "Day Book (Roznamcha)",
        "free_tier" to "Free Plan",
        "pro_tier" to "Pro Tier (₹99/mo)",
        "change_language" to "Change Language",
        "gst_mode_banner" to "Non-GST Mode: Showing simple bills without taxes",
        "gst_enabled_banner" to "GST Mode Active: CGST/SGST enabled with HSN codes",
        "settled" to "Settled"
    )

    private val hindiStrings = mapOf(
        "app_title" to "हिसाब प्रो",
        "home" to "होम",
        "sales" to "बिक्री (Sales)",
        "parties" to "पार्टी (खाता)",
        "reports" to "रिपोर्ट्स",
        "more" to "सेटिंग्स",
        "business_setup" to "व्यापार सेटअप",
        "business_name" to "दुकान / व्यापार का नाम",
        "phone_number" to "मोबाइल नंबर",
        "address" to "पता",
        "state" to "राज्य",
        "gst_registered_q" to "क्या GST रजिस्टर्ड व्यापार है?",
        "gstin" to "GSTIN नंबर",
        "pan" to "पैन नंबर",
        "composition_scheme" to "कंपोजिशन स्कीम",
        "save_details" to "सुरक्षित करें",
        "todays_sales" to "आज की बिक्री",
        "total_receivables" to "कुल लेना बाकी",
        "you_will_get" to "लेना है (Dr)",
        "total_payables" to "कुल देना बाकी",
        "you_will_give" to "देना है (Cr)",
        "cash_bank_balance" to "रोकड़ व बैंक बैलेंस",
        "quick_actions" to "तुरंत कार्य",
        "add_sale" to "+ नया बिल बनाएं",
        "receive_payment" to "+ भुगतान प्राप्त करें",
        "add_party" to "+ नया ग्राहक/पार्टी",
        "add_expense" to "+ खर्च जोड़ें",
        "recent_invoices" to "हाल के बिल",
        "no_invoices" to "अभी कोई बिल नहीं बना है",
        "customers" to "ग्राहक (Customers)",
        "suppliers" to "व्यापारी (Suppliers)",
        "opening_balance" to "प्रारंभिक शेष (Opening)",
        "current_balance" to "वर्तमान शेष",
        "add_new_party" to "नया खाता जोड़ें",
        "customer" to "ग्राहक",
        "supplier" to "सप्लायर",
        "both" to "दोनों",
        "receivable_dr" to "लेना बाकी (Dr)",
        "payable_cr" to "देना बाकी (Cr)",
        "create_invoice" to "बिक्री बिल बनाएं",
        "invoice_no" to "बिल संख्या",
        "date" to "दिनांक",
        "select_party" to "ग्राहक चुनें",
        "non_gst_bill" to "बिना GST बिल (सरल)",
        "gst_tax_invoice" to "GST टैक्स इनवॉइस",
        "item_name" to "सामान का नाम",
        "qty" to "मात्रा (Qty)",
        "unit" to "इकाई (Unit)",
        "rate" to "दर (₹)",
        "amount" to "रकम",
        "add_item" to "+ सामान जोड़ें",
        "subtotal" to "उप-योग",
        "cgst" to "CGST",
        "sgst" to "SGST",
        "igst" to "IGST",
        "total_amount" to "कुल राशि",
        "paid_amount" to "जमा राशि",
        "balance_due" to "बाकी रकम",
        "payment_mode" to "भुगतान प्रकार",
        "save_invoice" to "बिल सुरक्षित करें",
        "payment_received" to "भुगतान जमा (रसीद)",
        "received_from" to "किससे प्राप्त हुआ",
        "reference_no" to "रेफरेंस / UPI नंबर",
        "notes" to "विवरण / नोट",
        "save_payment" to "जमा दर्ज करें",
        "daily_sales" to "दैनिक बिक्री",
        "outstanding_report" to "बाकी उधारी रिपोर्ट",
        "day_book" to "दैनिक रोजनामचा",
        "free_tier" to "फ्री प्लान",
        "pro_tier" to "प्रो प्लान (₹99/माह)",
        "change_language" to "भाषा बदलें",
        "gst_mode_banner" to "नॉन-GST मोड: बिना टैक्स साधारण बिल",
        "gst_enabled_banner" to "GST मोड सक्रिय: CGST/SGST एवं HSN कोड के साथ",
        "settled" to "बराबर (Settled)"
    )

    private val marathiStrings = mapOf(
        "app_title" to "हिशोब प्रो",
        "home" to "मुख्य पान",
        "sales" to "विक्री (Sales)",
        "parties" to "खातेदार (Parties)",
        "reports" to "अहवाल (Reports)",
        "more" to "अधिक",
        "business_setup" to "व्यवसाय सेटअप",
        "business_name" to "दुकान / व्यवसायाचे नाव",
        "phone_number" to "मोबाईल नंबर",
        "address" to "पत्ता",
        "state" to "राज्य",
        "gst_registered_q" to "GST नोंदणीकृत व्यवसाय आहे का?",
        "gstin" to "GSTIN क्रमांक",
        "pan" to "पॅन क्रमांक",
        "composition_scheme" to "कंपोझिशन योजना",
        "save_details" to "जतन करा",
        "todays_sales" to "आजची विक्री",
        "total_receivables" to "एकूण येणे बाकी",
        "you_will_get" to "येणे आहे (Dr)",
        "total_payables" to "एकूण देणे बाकी",
        "you_will_give" to "देणे आहे (Cr)",
        "cash_bank_balance" to "रोख व बँक शिल्लक",
        "quick_actions" to "जलद क्रिया",
        "add_sale" to "+ विक्री बिल",
        "receive_payment" to "+ जमा पावती",
        "add_party" to "+ नवीन ग्राहक/पार्टी",
        "add_expense" to "+ खर्च नोंदवा",
        "recent_invoices" to "अलिकडील बिले",
        "no_invoices" to "अद्याप बिले तयार केलेली नाहीत",
        "customers" to "ग्राहक (Customers)",
        "suppliers" to "व्यापारी (Suppliers)",
        "opening_balance" to "प्रारंभिक शिल्लक (Opening)",
        "current_balance" to "चालू शिल्लक",
        "add_new_party" to "नवीन खाते जोडा",
        "customer" to "ग्राहक",
        "supplier" to "सप्लायर",
        "both" to "दोन्ही",
        "receivable_dr" to "येणे बाकी (Dr)",
        "payable_cr" to "देणे बाकी (Cr)",
        "create_invoice" to "विक्री बिल बनवा",
        "invoice_no" to "बिल क्रमांक",
        "date" to "तारीख",
        "select_party" to "ग्राहक निवडा",
        "non_gst_bill" to "विना-GST बिल (साधे)",
        "gst_tax_invoice" to "GST टॅक्स इनव्हॉइस",
        "item_name" to "मालाचे नाव",
        "qty" to "नग/प्रमाण (Qty)",
        "unit" to "युनिट",
        "rate" to "दर (₹)",
        "amount" to "रक्कम",
        "add_item" to "+ माल जोडा",
        "subtotal" to "एकूण उप-रक्कम",
        "cgst" to "CGST",
        "sgst" to "SGST",
        "igst" to "IGST",
        "total_amount" to "एकूण रक्कम",
        "paid_amount" to "जमा रक्कम",
        "balance_due" to "बाकी रक्कम",
        "payment_mode" to "पेमेंट पद्धत",
        "save_invoice" to "बिल जतन करा",
        "payment_received" to "पैसे जमा पावती",
        "received_from" to "कोणाकडून मिळाले",
        "reference_no" to "संदर्भ / UPI क्रमांक",
        "notes" to "टीप / तपशील",
        "save_payment" to "जमा नोंदवा",
        "daily_sales" to "दैनंदिन विक्री",
        "outstanding_report" to "बाकी उधारी अहवाल",
        "day_book" to "रोजकीर्द (रोजनामचा)",
        "free_tier" to "मोफत प्लॅन",
        "pro_tier" to "प्रो प्लॅन (₹९९/महिना)",
        "change_language" to "भाषा बदला",
        "gst_mode_banner" to "विना-GST मोड: कराशिवाय साधे बिल",
        "gst_enabled_banner" to "GST मोड सक्रिय: CGST/SGST सह",
        "settled" to "हिशोब पूर्ण (Settled)"
    )
}
